nodeLinker: node-modules

# Tăng tốc độ cài đặt
enableGlobalCache: true

# Sử dụng network timeout dài hơn cho các package lớn
networkTimeout: 300000

# Tự động cài đặt peer dependencies
enableStrictSsl: true

# Log level
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard
