/**
 * Định nghĩa các token injection chung cho toàn ứng dụng
 */

/**
 * Redis Tokens
 */
export const REDIS_CLIENT = 'REDIS_CLIENT'
export const REDIS_SERVICE = 'REDIS_SERVICE'

/**
 * Auth Tokens
 */
export const AUTH_PROVIDER = 'AUTH_PROVIDER'
export const TOKEN_SERVICE = 'TOKEN_SERVICE'
export const USER_AUTH_SERVICE = 'USER_AUTH_SERVICE'
export const OTP_SERVICE_TOKEN = 'OTP_SERVICE_TOKEN'
export const SESSION_SERVICE = 'SESSION_SERVICE'
export const DEVICE_SERVICE = 'DEVICE_SERVICE'
export const COOKIE_SERVICE = 'COOKIE_SERVICE'
export const RECOVERY_CODE_SERVICE = 'RECOVERY_CODE_SERVICE'
export const SOCIAL_AUTH_SERVICE = 'SOCIAL_AUTH_SERVICE'
export const TWO_FACTOR_SERVICE = 'TWO_FACTOR_SERVICE'

// Repositories
export const USER_REPOSITORY = 'USER_REPOSITORY'
export const DEVICE_REPOSITORY = 'DEVICE_REPOSITORY'
export const SESSION_REPOSITORY = 'SESSION_REPOSITORY'
export const RECOVERY_CODE_REPOSITORY = 'RECOVERY_CODE_REPOSITORY'

// Services
export const HASHING_SERVICE = 'HASHING_SERVICE'
export const EMAIL_SERVICE = 'EMAIL_SERVICE'
export const CACHE_MANAGER = 'CACHE_MANAGER'
export const PRISMA_SERVICE = 'PRISMA_SERVICE'
export const LOGGER_SERVICE = 'LOGGER_SERVICE'
export const GEOLOCATION_SERVICE = 'GEOLOCATION_SERVICE'

// Other
export const CONFIG_SERVICE = 'CONFIG_SERVICE'
export const I18N_SERVICE = 'I18N_SERVICE'

// Auth related tokens
export const AUTH_SERVICE = 'AUTH_SERVICE'
export const USER_AUTH_REPO = 'USER_AUTH_REPO'
export const DEVICE_REPO = 'DEVICE_REPO'
export const SESSION_REPO = 'SESSION_REPO'
export const RECOVERY_CODE_REPO = 'RECOVERY_CODE_REPO'

export const STRIPE_SERVICE = 'STRIPE_SERVICE'
export const SLT_SERVICE = 'SLT_SERVICE'
