// Services
export const PRISMA_SERVICE = 'PRISMA_SERVICE'
export const HASHING_SERVICE = 'HASHING_SERVICE'
export const TOKEN_SERVICE = 'TOKEN_SERVICE'
export const EMAIL_SERVICE = 'EMAIL_SERVICE'
export const TWO_FACTOR_SERVICE = 'TWO_FACTOR_SERVICE'
export const COOKIE_SERVICE = 'COOKIE_SERVICE'
export const CRYPTO_SERVICE = 'CRYPTO_SERVICE'
export const SESSION_SERVICE = 'SESSION_SERVICE'
export const USER_AGENT_SERVICE = 'USER_AGENT_SERVICE'
export const REDIS_SERVICE = 'REDIS_SERVICE'
export const GEOLOCATION_SERVICE = 'GEOLOCATION_SERVICE'
export const DEVICE_FINGERPRINT_SERVICE = 'DEVICE_FINGERPRINT_SERVICE'
export const SLT_SERVICE = 'SLT_SERVICE'
export const IMPORT_EXPORT_SERVICE = 'IMPORT_EXPORT_SERVICE'

// Repositories
export const SHARED_USER_REPOSITORY = 'SHARED_USER_REPOSITORY'

// Guards
export const ACCESS_TOKEN_GUARD = 'ACCESS_TOKEN_GUARD'
export const API_KEY_GUARD = 'API_KEY_GUARD'
export const AUTHENTICATION_GUARD = 'AUTHENTICATION_GUARD'
