# Elasticsearch Configuration for Production
# OPTIMIZED FOR 30 CORES - 20GB CONTAINER - 50K+ USERS

# Node Configuration
node.roles: [master, data, ingest]

# Network Settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery Settings
discovery.type: single-node
discovery.seed_hosts: []

# Security Settings
xpack.security.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false
xpack.security.enrollment.enabled: false

# Memory and Performance (OPTIMIZED FOR 50K+ USERS - 20GB container)
indices.memory.index_buffer_size: 30%
indices.queries.cache.size: 25%
indices.fielddata.cache.size: 25%

# Node Settings
action.destructive_requires_name: true
action.auto_create_index: false

# Memory Lock Settings
bootstrap.memory_lock: false

# Store Settings
node.store.allow_mmap: false

# Machine Learning
xpack.ml.enabled: false

# Ingest
ingest.geoip.downloader.enabled: false

# Snapshot and Restore
path.repo: ['/usr/share/elasticsearch/data/snapshots']

# Logging
logger.level: INFO
logger.org.elasticsearch.transport: WARN
logger.org.elasticsearch.discovery: WARN

# Thread Pool Settings (OPTIMIZED FOR 30 CORES - 20GB container)
thread_pool.write.size: 6
thread_pool.write.queue_size: 5000
thread_pool.search.size: 6
thread_pool.search.queue_size: 5000
thread_pool.get.size: 6
thread_pool.get.queue_size: 2000
thread_pool.analyze.size: 6
thread_pool.analyze.queue_size: 2000

# Circuit Breaker Settings (OPTIMIZED FOR 20GB RAM)
indices.breaker.total.limit: 80%
indices.breaker.fielddata.limit: 50%
indices.breaker.request.limit: 70%

# Recovery Settings (OPTIMIZED FOR HIGH THROUGHPUT)
indices.recovery.max_bytes_per_sec: 200mb
indices.recovery.max_concurrent_file_chunks: 8

# Network settings
http.max_content_length: 100mb
http.max_header_size: 8kb
http.max_initial_line_length: 4kb
