// Định nghĩa các mã lỗi validation chuẩn
export const VALIDATION_MESSAGES = {
  // Lỗi chung
  INVALID_INPUT: 'ERROR.INVALID_INPUT',
  REQUIRED_FIELD: 'ERROR.REQUIRED_FIELD',
  SERVER_ERROR: 'ERROR.SERVER_ERROR',

  // Lỗi xác thực
  INVALID_EMAIL: 'ERROR.INVALID_EMAIL',
  INVALID_PASSWORD: 'ERROR.INVALID_PASSWORD',
  PASSWORD_MISMATCH: 'ERROR.PASSWORD_MISMATCH',
  EMAIL_ALREADY_EXISTS: 'ERROR.EMAIL_ALREADY_EXISTS',
  EMAIL_NOT_FOUND: 'ERROR.EMAIL_NOT_FOUND',

  // Lỗi OTP
  INVALID_OTP: 'ERROR.INVALID_OTP',
  OTP_EXPIRED: 'ERROR.OTP_EXPIRED',
  INVALID_OTP_TOKEN: 'ERROR.INVALID_OTP_TOKEN',
  OTP_TOKEN_EXPIRED: 'ERROR.OTP_TOKEN_EXPIRED',

  // Lỗi token
  INVALID_TOKEN: 'ERROR.INVALID_TOKEN',
  TOKEN_EXPIRED: 'ERROR.TOKEN_EXPIRED',
  UNAUTHORIZED: 'ERROR.UNAUTHORIZED',

  // Lỗi 2FA
  TOTP_ALREADY_ENABLED: 'ERROR.TOTP_ALREADY_ENABLED',
  TOTP_NOT_ENABLED: 'ERROR.TOTP_NOT_ENABLED',
  INVALID_TOTP: 'ERROR.INVALID_TOTP'
}

// Hàm helper để truy xuất mã lỗi
export const getValidationMessage = (key: keyof typeof VALIDATION_MESSAGES) => {
  return VALIDATION_MESSAGES[key]
}

// Các hằng số lỗi để sử dụng trong code
export const ERROR_CODES = {
  VALIDATION: {
    INVALID_EMAIL: VALIDATION_MESSAGES.INVALID_EMAIL,
    INVALID_PASSWORD: VALIDATION_MESSAGES.INVALID_PASSWORD,
    PASSWORD_MISMATCH: VALIDATION_MESSAGES.PASSWORD_MISMATCH,
    EMAIL_ALREADY_EXISTS: VALIDATION_MESSAGES.EMAIL_ALREADY_EXISTS,
    EMAIL_NOT_FOUND: VALIDATION_MESSAGES.EMAIL_NOT_FOUND
  },
  AUTH: {
    INVALID_OTP: VALIDATION_MESSAGES.INVALID_OTP,
    OTP_EXPIRED: VALIDATION_MESSAGES.OTP_EXPIRED,
    INVALID_OTP_TOKEN: VALIDATION_MESSAGES.INVALID_OTP_TOKEN,
    OTP_TOKEN_EXPIRED: VALIDATION_MESSAGES.OTP_TOKEN_EXPIRED,
    INVALID_TOKEN: VALIDATION_MESSAGES.INVALID_TOKEN,
    TOKEN_EXPIRED: VALIDATION_MESSAGES.TOKEN_EXPIRED,
    UNAUTHORIZED: VALIDATION_MESSAGES.UNAUTHORIZED
  },
  TOTP: {
    ALREADY_ENABLED: VALIDATION_MESSAGES.TOTP_ALREADY_ENABLED,
    NOT_ENABLED: VALIDATION_MESSAGES.TOTP_NOT_ENABLED,
    INVALID: VALIDATION_MESSAGES.INVALID_TOTP
  }
}
