global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: shopsifu-production
    environment: production
    application: shopsifu
    datacenter: primary

# Alerting rules
rule_files:
  - 'rules/*.yml'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus tự monitor
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # ShopSifu API Server - Performance monitoring
  - job_name: 'shopsifu-api'
    static_configs:
      - targets: ['shopsifu_server:3000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'api-server'

  # PostgreSQL với postgres_exporter - Database performance
  - job_name: 'postgres'
    static_configs:
      - targets: ['shopsifu_postgres_exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'postgresql'

  # Redis với redis_exporter - Cache performance
  - job_name: 'redis'
    static_configs:
      - targets: ['shopsifu_redis_exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'redis'

  # Elasticsearch - Search performance (commented out - no metrics endpoint)
  # - job_name: 'elasticsearch'
  #   static_configs:
  #     - targets: ['shopsifu_elasticsearch:9200']
  #   metrics_path: /_prometheus/metrics
  #   scrape_interval: 30s
  #   scrape_timeout: 15s
  #   honor_labels: true
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance
  #       regex: '([^:]+)(?::\d+)?'
  #       replacement: '${1}'
  #     - source_labels: [__address__]
  #       target_label: service
  #       replacement: 'elasticsearch'

  # Node Exporter cho system metrics - Infrastructure monitoring
  - job_name: 'node'
    static_configs:
      - targets: ['shopsifu_node_exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'system'

  # cAdvisor cho container metrics - Container performance
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['shopsifu_cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'containers'

  # Blackbox exporter cho uptime monitoring - Availability monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://shopsifu_server:3000/health
          - http://shopsifu_server:3000/metrics
          - http://shopsifu_server:3000/api/status
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: shopsifu_blackbox:9115
      - source_labels: [__param_target]
        target_label: service
        replacement: 'api-endpoints'

  # Blackbox exporter cho database connectivity
  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - shopsifu_postgres:5432
          - shopsifu_redis:6379
          - shopsifu_elasticsearch:9200
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: shopsifu_blackbox:9115
      - source_labels: [__param_target]
        target_label: service
        replacement: 'database-connectivity'

  # PgBouncer monitoring - Connection pooling performance (commented out - no metrics endpoint)
  # - job_name: 'pgbouncer'
  #   static_configs:
  #     - targets: ['shopsifu_pgbouncer:6432']
  #   metrics_path: /metrics
  #   scrape_interval: 30s
  #   scrape_timeout: 10s
  #   honor_labels: true
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance
  #       regex: '([^:]+)(?::\d+)?'
  #       replacement: '${1}'
  #     - source_labels: [__address__]
  #       target_label: service
  #       replacement: 'pgbouncer'

  # Grafana monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['shopsifu_grafana:3000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'grafana'

  # Kibana monitoring (commented out - no metrics endpoint)
  # - job_name: 'kibana'
  #   static_configs:
  #     - targets: ['shopsifu_kibana:5601']
  #   metrics_path: /api/status
  #   scrape_interval: 30s
  #   scrape_timeout: 10s
  #   honor_labels: true
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance
  #       regex: '([^:]+)(?::\d+)?'
  #       replacement: '${1}'
  #     - source_labels: [__address__]
  #       target_label: service
  #       replacement: 'kibana'
