# Simple Prometheus Configuration for Shopsifu
global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  # Self monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Shopsifu API
  - job_name: 'shopsifu-api'
    static_configs:
      - targets: ['server:3000']
    metrics_path: '/health'
    scrape_interval: 15s
