name: 🔄 Rollback Production

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA để rollback (để trống để rollback về commit trước)'
        required: false
        default: ''
      reason:
        description: 'Lý do rollback'
        required: false
        default: 'Manual rollback'

env:
  VPS_HOST: ${{ secrets.VPS_HOST }}
  VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
  VPS_PATH: ${{ secrets.VPS_PATH }}

jobs:
  rollback:
    name: 🔄 Rollback Application
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔄 Perform rollback
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -euo pipefail
            cd "${{ env.VPS_PATH }}"

            echo "🔄 Starting rollback process..."

            # Get current commit
            CURRENT_COMMIT=$(git rev-parse HEAD)
            echo "Current commit: $CURRENT_COMMIT"

            # Determine target commit
            TARGET_COMMIT="${{ github.event.inputs.commit_sha }}"
            if [ -z "$TARGET_COMMIT" ]; then
              TARGET_COMMIT=$(git rev-parse HEAD~1)
              echo "Rolling back to previous commit: $TARGET_COMMIT"
            else
              echo "Rolling back to specified commit: $TARGET_COMMIT"
            fi

            # Verify target commit exists
            if ! git rev-parse --verify "$TARGET_COMMIT" >/dev/null 2>&1; then
              echo "❌ Target commit $TARGET_COMMIT does not exist"
              exit 1
            fi

            # Verify target commit is different from current
            if [ "$CURRENT_COMMIT" = "$TARGET_COMMIT" ]; then
              echo "❌ Target commit is same as current commit"
              exit 1
            fi

            # Create backup branch before rollback
            BACKUP_BRANCH="backup-$(date +%Y%m%d-%H%M%S)"
            git checkout -b "$BACKUP_BRANCH"
            echo "✅ Created backup branch: $BACKUP_BRANCH"

            # Create emergency backup before rollback
            echo "🗄️ Creating emergency backup before rollback..."
            BACKUP_TIMESTAMP=$(date +%Y%m%d_%H%M%S)

            # Backup current database state
            docker exec shopsifu_postgres.1 pg_dump -U shopsifu -d shopsifu --format=custom --file=/tmp/emergency_backup_$BACKUP_TIMESTAMP.backup
            docker cp shopsifu_postgres.1:/tmp/emergency_backup_$BACKUP_TIMESTAMP.backup /backup/shopsifu/database/

            # Backup current config
            tar -czf /backup/shopsifu/config/emergency_config_$BACKUP_TIMESTAMP.tar.gz config/ monitoring/ .env.docker docker-compose.swarm.yml

            echo "✅ Emergency backup created: emergency_backup_$BACKUP_TIMESTAMP.backup"

            # Switch back to main and perform rollback
            git checkout main
            git reset --hard "$TARGET_COMMIT"
            echo "✅ Git reset completed"

            # Deploy with Docker Swarm
            echo "🚀 Redeploying with Docker Swarm..."
            ./scripts/deploy-swarm.sh

            echo "✅ Rollback completed successfully"

  health-check:
    name: 🏥 Verify Rollback
    needs: rollback
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 🏥 Health check after rollback
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -euo pipefail

            echo "🏥 Verifying rollback health..."
            ATTEMPTS=15
            SLEEP=4

            for i in $(seq 1 $ATTEMPTS); do
              echo "Attempt $i/$ATTEMPTS..."
              if curl -fsS -m 5 http://localhost:3000/health > /dev/null; then
                echo "✅ Health check passed after rollback!"
                exit 0
              fi
              sleep $SLEEP
            done

            echo "❌ Health check failed after rollback"
            exit 1

  notification:
    name: 📢 Rollback Notification
    needs: [rollback, health-check]
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: always()
    steps:
      - name: 📢 Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          STATUS: ${{ needs.health-check.outcome == 'success' && 'success' || 'failure' }}
          REASON: ${{ github.event.inputs.reason }}
          COMMIT_SHA: ${{ github.event.inputs.commit_sha }}
        run: |
          sudo apt-get update && sudo apt-get install -y jq

          COLOR=$([ "$STATUS" = "success" ] && echo 15105570 || echo 15158332)
          ICON=$([ "$STATUS" = "success" ] && echo "✅" || echo "❌")
          DESCRIPTION=$([ "$STATUS" = "success" ] && echo "🔄 **Rollback thành công**" || echo "❌ **Rollback thất bại**")

          JSON_PAYLOAD=$(jq -n \
            --arg status "$STATUS" \
            --arg icon "$ICON" \
            --arg description "$DESCRIPTION" \
            --arg reason "$REASON" \
            --arg commit_sha "$COMMIT_SHA" \
            --arg color "$COLOR" \
            ' {
                embeds: [{
                  title: "🔄 SERVER - Rollback Production",
                  description: $description,
                  color: ($color | tonumber),
                  fields: [
                    { name: "📊 Trạng thái", value: "\($icon) \($status | ascii_upcase)", inline: true },
                    { name: "📝 Lý do", value: $reason, inline: false }
                  ],
                  footer: { "text": "🔄 Rollback Production" },
                  timestamp: (now | strftime("%Y-%m-%dT%H:%M:%SZ"))
                }]
              }')

          curl -s -H "Content-Type: application/json" -X POST -d "$JSON_PAYLOAD" "$DISCORD_WEBHOOK" || echo "Lỗi gửi thông báo Discord"
