import { Inject, Injectable, Logger } from '@nestjs/common'
import { I18nService } from 'nestjs-i18n'
import { I18nTranslations } from 'src/generated/i18n.generated'
import { UserRepository } from 'src/routes/user/user.repository'
import { HASHING_SERVICE } from 'src/shared/constants/injection.tokens'
import { HashingService } from 'src/shared/services/hashing.service'
import { ProfileResponseDto, UpdateProfileDto } from '../profile.dto'
import { ProfileError } from '../profile.error'
import { ProfileRepository } from '../profile.repository'
